olhkyle/Bpple

client/src/components/Root.jsx, client/src/components/common/index.js, client/src/components/index.js
=> [FEAT] components index 페이지 추가

client/src/components/common/Header.jsx, client/src/components/common/index.js, client/src/components/community/CommunityHeader.jsx, client/src/components/community/index.js, client/src/constants/routes.js, client/src/styles/GlobalStyle.js
---
- Header 컴포넌트 완료
- CommunityHeader 컴포넌트 완료
- dark, light 테마별 hover-font-color 추가
- routes 추가
- 커뮤니티 - 질문하기 (/community/question)
- 커뮤니티 - 랭킹 (/community/rank)
- 커뮤니티 - 내가 작성한 글 목록 (/community/me)
=> Common components sunhwa

client/src/components/common/Footer.jsx, client/src/components/common/PopupModal.jsx, client/src/styles/GlobalStyle.js
---
- `Footer` 컴포넌트 스타일 수정
- `PopupModal` 컴포넌트 생성 완료
- GlobalStyle.js `footer-font-color` 스타일 추가
=> [FEAT] : Popup Modal Component

client/src/components/common/PopupModal.jsx
---
- PopupModal 공통 컴포넌트 title prop type `ReactNode` => `string | undefined'로 수정
=> [FIX] : PopupModal title prop 수정

client/src/styles/GlobalStyle.js
---
- `GlobalStyle.js` css 전역변수 추가
- `--opacity-bg-color: #e5e5e520;`
- `--opacity-border-color: #e5e5e5;`
=> [STYLE] :  GlobalStyle opacity-color 추가

client/src/components/common/Header.jsx, client/src/components/common/TextCard.jsx, client/src/components/common/index.js, client/src/components/community/RuleModal.jsx
---
- TextCard 컴포넌트 완료
- PopupModal index 추가
- Header 컴포넌트 - 메모 주석 제거
=> [Feat] TextCard 컴포넌트  

client/src/components/auth/SingUp/SignUp.jsx, client/src/components/auth/SingUp/SignUpForm.jsx, client/src/components/auth/SingUp/index.js, client/src/pages/SignUp.jsx, server/mock-data/users.js, server/router/auth.js
---
- 회원가입 폼에 맞게 user 데이터 구조 수정 필요
- 이메일 / 닉네임 중복 검사하는 api 필요
---
- users mock 데이터 수정 및 메서드 추가
- users에 createuser 메서드 인수를 userInfo로 변경
- /checkemail , / checknickname 메서드 추가
- /signup 페이로드 userInfo로 변경
---
-
=> Server junpyo

client/src/App.jsx, client/src/components/auth/SignIn/EmailInput.jsx
---
- Main 접근 시, SignIn 페이지로 이동하는 기능 삭제
- SignIn 페이지 이메일 input placeholder 추가
=> router 수정 / placeholder 추가

client/src/components/Root.jsx, client/src/components/common/Footer.jsx, client/src/components/community/CommunityMyPosts.jsx, client/src/components/community/CommunityPosts.jsx, client/src/components/community/index.js, client/src/pages/CommunityMe.jsx, client/src/styles/GlobalStyle.js
---
- `Root.jsx`에서 div 요소 main 요소로 변경
- `footer` 스타일 수정
- padding 수정
- `CommunityMe` 페이지 컴포넌트 생성
- `CommunityMyPosts`, `CommunityPosts` 컴포넌트 생성 및 스타일 적용
- Community 컴포넌트 디렉토리 내 `index.js`에 관련 컴포넌트 import 추가
- `GlobalStyle.js` => `body: background-color` css 변수 적용
---
- 내가 작성한 글 목록 ( CommunityMe 페이지 컴포넌트 ) 관련 api 작업
=> [Feat] : CommunityMe 페이지 

client/src/App.jsx, client/src/components/community/CommunityMain.jsx, client/src/components/community/index.js, client/src/pages/Community.jsx, client/src/pages/CommunityMe.jsx, client/src/pages/index.js
---
- `Community` 페이지 생성
- community 디렉토리 `index.js`에 `CommunityMain` 컴포넌트 추가
- page 디렉토리 `index.js` `Community, CommunityMe` 페이지 컴포넌트 추가
- `CommunityMe` 페이지 컴포넌트 수정
- `Community` 페이지 관련 라우팅 추가
=> [Feat] : Community Main 페이지 컴포넌트

client/src/components/community/CommunityPosts.jsx
=> [-] ProfileAvatar 파일 위치 수정

server/mock-data/users.js, server/package.json, server/router/auth.js, server/test.rest
---
- 로그아웃 기능 추가
- uuid 라이브러리 추가
- 유저 데이터 정보 변경
```js
let users = [
{
id: uuidv4(),
firstName: '서',
lastName: '준표',
country: '대한민국',
birthDate: new Date('1995-09-15'),
email: 'cooljp95@naver.com',
password: 'ABcdef12',
nickName: '서준표',
phoneNumber: '010-2395-9282',
products: [],
point: 0,
level: 0,
avatar: null,
},
];
```
=> 로그아웃 기능 추가 / 유저 데이터 정보 변경

server/mock-data/users.js
=> [FIX] 레벨 기본값 설정

client/src/components/common/Card.jsx, client/src/components/common/Toast.jsx
---
- Toast 구현 완료 
```
/**
* h : toast의 height값 / string
* c : toast 폰트 컬러 / string
* bgc : toast 배경 컬러 / string
*
* fixed : toast fixed 속성 여부 / boolean
*         true일 경우 상단 / 하단에 고정되서 등장
*         false일 경우 아래 요소들을 밀어내면서 등장
*
* position : toast가 등장할 위치  / 'top' | 'bottom'
* closeOnClick : toast 닫기 버튼 노출 여부 / boolean
* autoClose : 딜레이 이후 자동으로 toast 삭제 여부 / boolean
* autoCloseDelay : 자동으로 toast 삭제 시, 딜레이 지정 / number
* children : toast에 포함할 내용 / jsx
*
* @param {{h, c, bgc, fixed, position, closeOnClick, autoClose, autoCloseDelay, children}}
* @returns
*/
```
- 카드 구현 완료
```
/**
* to : Link태그의 to 프로퍼티, 클릭 시 이동할 경로 선택 / string
* size : 카드 사이즈 / xs | sm | md | lg | xl
* bg : 카드 배경 컬러
* children : 카드 내용
* @param {to, size, bg, children} param0
* @returns
*/
```
=> [FEAT] Toast / Card 구현 완료

client/src/components/common/nav/SubMenu.jsx, client/src/styles/GlobalStyle.js
---
- submenu 컴포넌트 --secondary-bg-color 추가 및 적용
=> [STYLE] : --secondary-bg-color 추가 및 적용

client/src/api/auth.js
=> [FIX] 로그인 에러 문제 해결

server/mock-data/posts.js, server/router/post.js, server/test/post.rest
=> [FEAT] search api 추가

client/src/api/auth.js, client/src/components/auth/SignIn/SignInForm.jsx, client/src/components/common/nav/LoginButton.jsx, server/mock-data/users.js
---
- 로그인 시 MAIN으로 이동 및 로그인 사용자 정보 전역 상태 저장
- 로그아웃 api 및 기능 추가
=> [FEAT] Signout

client/index.html, client/src/App.jsx, client/src/api/profile.js, client/src/guard/AuthenticationGuard.jsx, client/src/pages/Profile.jsx, server/router/auth.js, server/router/profile.js
---
**server**
- 사용자 인증시 사용자 정보 전송 (email, avatarId, nickName)
- profile router - 사용자 프로필 정보 전송
**client**
- AuthenticationGuard 추가
- router - Profile 페이지 추가
- Profile 페이지 추가
=> [FEAT] Profile

client/src/App.jsx
---
- queryClient defaultOptions 설정 항목 위치 변경
=> [REFACTOR] : queryClient defaultOptions 설정 항목 위치 변경

client/src/components/community/AutoComplete.jsx
---
- `<AutoComplete/>` data-hovered 관련 스타일 수정
- `onSubmit` 이벤트 발생 시 해당 게시물 페이지로 이동하는 로직 추가
=> [FEAT] : AutoComplete data-hovered 관련 스타일 수정 및  onSubmit 이벤트 설정

client/src/components/community/AutoComplete.jsx
---
- `<AutoCompleteItem/>` data-hovered 관련 스타일 및 접근성 수정
=> [STYLE] : data-hovered 관련 스타일 및 접근성 수정

client/src/App.jsx, client/src/components/community/CommunityMyPosts.jsx, client/src/components/community/index.js, client/src/hooks/useAutoCompleteQuery.js, client/src/pages/CommunityMe.jsx, client/src/pages/index.js
---
- 401 error 관련 `suspense: true` 옵션 추가
- `CommunityPosts` 컴포넌트 변수명 변경
- index.js export 컴포넌트 추가
=> [FIX] : Suspense true 옵션 수정

client/src/pages/CommunityPost.jsx
=> [-] : CommunityPost 파일 추가

client/src/components/common/Form/PhoneNumberInput.jsx
---
- phoneNumber 최대 입력 문자열 길이 제한 추가
=> [FIX] phoneNumber 최대 입력 문자열 길이 제한 추가

client/src/components/auth/SignUp/SignUpForm.jsx, client/src/components/common/Form/BirthDateInput.jsx, client/src/components/common/Form/CountrySelect.jsx, client/src/components/common/Form/DuplicateCheckInput.jsx
---
- BirthDateInput
- BirthDateInput에서 Input과 DatePicker를 혼용하여 사용하던 것을 DateInput으로 통합
- 초기 Date를 설정가능하도록 변경 
- 날짜 선택 이후에 캘린더를 다시 킬 경우 선택된 날짜를 기준으로 랜더링되도록 변경
```jsx
<>
<Input
...
/>
{opened && (
<DatePicker
...
/>
)}
</>
```
```jsx
<DateInput
...
/>
```
```jsx
/**
* useForm의 register('inputName') props로 전달
* useForm의 setValue props로 전달
* placeholder설정 가능
* @param {{...register('inputName'), placeholder, setValue}, ref}
* 
* initDate 초기 띄울 날짜 설정
* @param {{...register('inputName'), placeholder, setValue, initDate}, ref}
* @returns
*/
```
- DuplicateCheckInput 
- { duplicate : boolean }를 가진 data를 받아  내부에서 중복 여부 체크하던 방식에서 boolean을 바로 받도록 변경.
```jsx
const { data } = await checker(e.target.value);
setDuplicated(data.duplicated);
```
```jsx
const duplicated = await checker(e.target.value); …
```
=> [FIX] BirthDateInput / DuplicateCheckInput 

client/src/components/auth/SignIn/SignInForm.jsx, client/src/components/auth/SignUp/SignUpForm.jsx, client/src/components/common/Form/InputWrapper.jsx, client/src/components/profile/UserProfileEditForm.jsx, client/src/components/profile/avatar/AvatarButton.jsx
---
- form(signup, signin, edit) field 라벨 추가
- style 리팩토링
=> [FIX] form label 추가 및 style 리팩토링

client/src/components/auth/SignIn/SignInForm.jsx, client/src/components/auth/SignUp/PasswordTooltipInput.jsx, client/src/components/auth/SignUp/SignUpForm.jsx, client/src/components/common/Form/InputWrapper.jsx, client/src/components/profile/UserProfileEditForm.jsx
---
- Form -> form 폴더명 변경
- STYLE 리팩토링
=> [-] STYLE 리팩토링 및 폴더명 변경

client/src/components/Root.jsx, client/src/components/common/Card.jsx, client/src/components/common/Footer.jsx, client/src/components/common/Form/BirthDateInput.jsx, client/src/components/common/InfoCard.jsx, client/src/components/common/Loader.jsx, client/src/components/common/ScrollToTopButton.jsx, client/src/components/common/Toast.jsx, client/src/components/community/AutoComplete.jsx, client/src/components/community/CommunityMain.jsx, client/src/components/community/CommunityMyPosts.jsx, client/src/components/profile/avatar/AvatarButton.jsx
---
- ScrollToTopButton 추가
- 스타일 컨벤션 통일
=> [STYLE] : 스타일 컨벤션 통일

client/src/components/community/CommunityMain.jsx
=> [FIX] : 중복 변수 제거

client/src/components/common/ScrollToTopButton.jsx, client/src/components/common/Toast.jsx
---
- `toast.jsx`, `ScrollToTopButton.jsx` translate3D 텍스트 포맷 수정
- Mantine `useWindowScroll` hook 사용
=> [REFACTOR] : useWindowScroll hook 사용

client/src/components/common/index.js
---
- `<FormInput/>` 컴포넌트 제거로 export 문 제거
=> [-] : FormInput 컴포넌트 제거로 export 문 제거

client/src/components/common/Card.jsx
=> [FIX] Card style 오류 수정

client/src/App.jsx, client/src/components/community/CategoryRadio.jsx, client/src/components/community/QuestionForm.jsx, client/src/components/community/TextEditor.jsx, client/src/components/community/index.js, client/src/pages/Question.jsx
---
- 기존 onBlur 발생 시 , setValue를 통해 RTE의 값을 취득하였으나, 해당 방법은 부적절하고 Submit 이벤트 발생 시 RTE의 값을 취득하길 원함
- Question page가 다른 page와 컨벤션이 맞지 않게 작성되어 있었음
---
- 변경사항입니다.
- useEditror의 인수로 넘기는 객체에 onUpdate라는 메서드를 정의해서 넘길 수 있었음
- 따라서 onUpdate의 메서드에 setValue를 넘겨 값을 취득하도록 변경.
- Question page에서 Question Form 부분을 컴포넌트로 분리
=> [REFACTOR] TextEditor onUpdate 추가 / Question Form 분리

server/mock-data/comments.js, server/mock-data/posts.js, server/router/post.js, server/router/posts.js, server/test/comment.rest, server/test/post.rest
=> [SEVER] comments 관련 API 추가

server/router/post.js
---
- post / comments 정보 요청 시, 유저 정보 일부 함께 전송.
=> [FIX] post / comments 정보 요청 시, 유저 정보 일부 함께 전송

client/src/components/common/Toast.jsx, client/src/components/community/SideFilter.jsx, client/src/components/community/index.js
---
- SIdeFilter 컴포넌트 추가
- Toast에 z-index 추가
=> [FEAT] SideFilter 컴포넌트 / Toast z-index 추가

server/router/posts.js, server/test/post.rest
---
- category post List 요청시. 댓글 수 / 아바타 id 같이 전송
=> [SEVER] category post List 요청시 , 댓글 수 / 아바타 id 같이 전송

client/src/components/common/avatar/AvatarEditModal.jsx, client/src/components/profile/UserProfileEditForm.jsx, server/router/profile.js
---
**client**
- 프로필 수정 - AvatarEditModal - Radio로 변경 (control)
**server**
- 프로필 - user 확인 로직 추가
=> [FEAT] 프로필 수정 AvatarEditModal - Radio로 변경

client/src/App.jsx, client/src/components/Layout.jsx, client/src/pages/Community.jsx
---
- 메인 페이지 index : true로 라우터 변경
---
- 커뮤니티 메인만 Page 폴더가 아닌 컴포넌트 폴더에 존재
- 추후 논의 후 파일 위치 이동 시킬지 결정하기
=> [FEAT] 메인 페이지 index : true로 라우터 변경

client/src/components/community/QuestionForm.jsx, client/src/components/community/SelectProductRadio.jsx, client/src/components/community/SubjectSelect.jsx, client/src/components/community/index.js
---
- Question Form에서 주제 선택하는 Radio 컴포넌트로 분리. 
- category와 productType을 Subject 객체 하나로 관리하도록 scheme 변경.
- 이에 따라 각각 분리해서 사용하던 useController를 하나로 통합하여 하나의  form으로 취급하도록 변경.
- 서버에 데이터 전송 시, 서버 전송 요청에 맞게 데이터 변조
=> Feat question page

client/src/App.jsx, client/src/components/community/CommunityCategorySection.jsx, client/src/components/community/CommunityMyPosts.jsx, client/src/components/community/SelectProductRadio.jsx, client/src/components/profile/ProfileInfo.jsx, client/src/components/profile/UserProfileEditForm.jsx, client/src/loader/communityCategoryLoader.js, client/src/loader/communityMeLoader.js, client/src/loader/communityPostLoader.js, client/src/loader/index.js, client/src/loader/profileLoader.js, client/src/loader/rankLoader.js, client/src/pages/CommunityCategory.jsx, client/src/pages/CommunityMe.jsx, client/src/pages/CommunityPost.jsx, client/src/pages/Profile.jsx, client/src/pages/Rank.jsx, client/src/pages/index.js, client/src/query/categoryQuery.js, client/src/query/communityMeQuery.js, client/src/query/communityPostQuery.js, client/src/query/index.js, client/src/query/profileQuery.js, client/src/query/rankQuery.js
---
-  loader, query 파일 분리  및 import 경로 수정.
=> [REACTOR] loader, query 파일 분리 

client/src/components/community/Comments.jsx, client/src/components/community/CommunityCategoryPosts.jsx, client/src/components/community/CommunityCategorySection.jsx
---
- `Divider` 조건부 렌더링 undefined 오류 문제 해결
- `CommunityCategorySection` 컴포넌트 분리 및 추상화
=> [FEAT] : CommunityCategorySection 컴포넌트 분리 및 추상화

client/src/components/community/CommunityCategorySection.jsx
---
- `categoryQuery` import 경로 수정
- emotion css Changing based on props
=> [FIX] : categoryQuery import 경로 수정

server/router/posts.js
=> [FEAT] community/me에 페이지 추가

client/src/components/community/CommunityCategorySection.jsx, client/src/components/community/Posts.jsx, client/src/components/community/SideFilter.jsx
---
- 카테고리 페이지와 게시물 총 갯수 디자인 통일.
=> [FIX] Posts 게시물 총 갯수 통일

server/mock-data/posts.js, server/router/post.js
---
- 글 작성 요청 시, postId 응답으로 전송
=> [FEAT] 글 작성 요청 시, postId 응답으로 전송

client/src/components/community/question/QuestionForm.jsx
---
- 글 작성 시, 작성된 post 페이지로 이동.
=> [FIX] 글 작성 시, 작성된 post 페이지로 이동

client/src/hooks/mutations/useAddCommentMutation.js, client/src/hooks/mutations/useCommentMutation.js, server/router/post.js
---
- 토큰 만료 / 토큰 없는 사용자가 댓글 작성 시 처리.
- 로그인 만료되었다는 토스트 노출, 
- 사용자 전역 상태 null로 변경
=> [FEAT] 토큰 만료 / 토큰 없는 사용자가 댓글 작성 시 처리

client/src/hooks/mutations/useAddCommentMutation.js, client/src/hooks/mutations/useCommentMutation.js, server/router/post.js
---
- 토큰 만료 / 토큰 없는 사용자가 댓글 상태 업데이트 시 처리.
- ( 삭제 , 편집, 유용함 업데이트 )
=> [FEAT] 토큰 만료 / 토큰 없는 사용자가 댓글 상태 업데이트 시 처리

client/src/components/community/AppleRecommendChip.jsx, client/src/components/community/comment/Comment.jsx, client/src/components/community/comment/Comments.jsx, client/src/pages/CommunityPostDetail.jsx, server/mock-data/users.js, server/router/post.js
---
- mock-data user 정보 role 추가 및 관리자 계정 추가
- Apple 권장 답변 채택 chip 구현 `AppleRecommendChip`
- `comments` 가져오는 server 코드 `role`이 admin인지 체크하는 코드로 수정
- 유용함 Badge UI 오류 해결 및 prop 추가
=> [FEAT] : APPLE 권장답변채택 chip 구현 및 관리자 계정 추가

server/mock-data/comments.js, server/mock-data/posts.js, server/router/post.js
=> [FEAT] 권장 답변 api 처리

client/src/components/community/comment/Comment.jsx, client/src/components/community/comment/CommentSection.jsx, client/src/constants/commentsQueryKey.js, client/src/hooks/mutations/useCommentMutation.js, client/src/hooks/mutations/usePostInfoMutation.js, client/src/hooks/mutations/useRemoveCommentMutation.js, client/src/hooks/mutations/useToggleCertifiedMutation.js, client/src/hooks/queries/useCommentsQuery.js, server/mock-data/comments.js, server/router/post.js
---
- 쿼리키 일치하도록 수정.
- 답변하기 버튼 클릭 시, 깜박거리는 현상 해결.
- 권장 답변 삭제 시, post 서버 / 캐시 데이터 업데이트.
=> [FIX]권장 답변 삭제 시, post 서버 / 캐시 데이터 업데이트

client/src/api/post.js, client/src/components/common/CommentLoader.jsx, client/src/components/common/index.js, client/src/components/community/DeletePostModal.jsx, client/src/components/community/PostContent.jsx, client/src/components/community/index.js, client/src/components/community/posts/PostSection.jsx, client/src/components/community/question/QuestionForm.jsx, client/src/components/profile/AvatarProfileInfo.jsx, client/src/components/profile/MyProfile.jsx, client/src/pages/CommunityPostDetail.jsx
=> [REFAC] : Real Final Refactor

client/src/components/common/form/CountrySelect.jsx, client/src/components/community/DeletePostModal.jsx, client/src/components/community/PostContent.jsx, client/src/components/profile/ProfileEditForm.jsx, server/mock-data/posts.js
=> [FIX] 버그 수정 / mock 데이터 수정

client/src/components/auth/SignInForm.jsx, client/src/components/auth/SignUpForm.jsx, client/src/pages/CommunityFaq.jsx, client/src/pages/SignIn.jsx
=> [REFAC] : style 수정 및 리팩토링

client/firebase/app.js, client/firebase/comments.js, client/firebase/posts.js, client/package-lock.json, client/package.json, client/src/components/community/DeletePostModal.jsx, client/src/components/community/posts/PostSection.jsx, client/src/components/community/question/QuestionForm.jsx, client/src/loaders/postDetailLoader.js, client/src/pages/CommunityPostDetail.jsx, client/src/queries/postDetailQuery.js
---
- firebase 연결.
- firebase 데이터 읽기 / 수정 코드 작성 ( posts, comments )
- 일부 firebase와 연결
=> [FEAT] firebase 연결

client/src/App.jsx
---
- Post 상세 페이지 경로 변경 (카테고리에 상관없이 /post/:postId)
=> [FIX] PostDetail route 경로 변경

client/src/App.jsx, client/src/pages/PopularPosts.jsx, client/src/pages/index.js, client/src/routes/routePaths.js
---
- PopularPosts 페이지 추가 (임시 빈 페이지)
- routePaths 경로 룰 수정 
- 인기글 페이지 : /대분류카테고리/list/popular 
- 서브카테고리 페이지 : /대분류카테고리/서브카테고리
=> [Feat] PopularPosts 페이지 추가
